sudo: false

language: go

go:
  - 1.13.x

go_import_path: github.com/corneliusweig/release-notes

install: true

notifications:
  email: false

before_install:
  - go mod download

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

script:
  - hack/run-lint.sh
  - go build ./
  - tar czf archive.tar.gz release-notes LICENSE

